function rv = calc_r(zc_0, zc_1, zpn_0, zpn_1, p, s, d, h, l_0, l_1, rho_0, beta_0, rho_1, beta_1)
% Calculate wheel dimension, from "3/5/20 - 5b"
r_0 = (zc_0 - zpn_0 + (h - l_0)*cos(beta_0)*cos(rho_0) + (s + d)*sin(rho_0) - p*sin(beta_0)*cos(rho_0)) / (cos(beta_0)*cos(rho_0));

r_1 = (zc_1 - zpn_1 - (h - l_0 - r_0)*(beta_1*sin(beta_0)*cos(rho_0) + ...
    rho_1*cos(beta_0)*sin(rho_0)) - l_1*cos(beta_0)*cos(rho_0) + ...
    (s + d)*rho_1*cos(rho_0) - ...
    p*(beta_1*cos(beta_0)*cos(rho_0) - rho_1*sin(beta_0)*sin(rho_0))) / ...
    (cos(beta_0)*cos(rho_0));

rv = [r_0; r_1];